### ISSUE TITLE
Set up github actions workflow

### ISSUE THREAD

**Issue by Louis-Finegan** [Louis-Finegan/Flask-Banking-Web-Application#4]
Workflow set up.

Docker Build and pull step must be implemented.

```
steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/bankapp:latest .
            docker push ${{ secrets.DOCKER_USERNAME }}/bankapp:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/bankapp:latest

```
